-- Comprehensive Supabase Schema for Veridi OS Sustainability Intelligence Platform
-- This schema integrates both the original power plant data and the new sustainability intelligence tables

-- ============================================================================
-- ORIGINAL POWER PLANT DATA TABLES
-- ============================================================================

-- Power plants table
create table if not exists public.power_plants (
    id bigint generated by default as identity primary key,
    plant_name text not null,
    plant_type text not null,
    capacity_mw numeric not null,
    location text,
    country text,
    commissioning_date date,
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

-- Power plant emissions data
create table if not exists public.power_plant_emissions (
    id bigint generated by default as identity primary key,
    plant_id bigint references public.power_plants(id) on delete cascade,
    timestamp timestamptz not null,
    co2_emissions_tonnes numeric not null,
    power_output_mw numeric not null,
    efficiency_pct numeric,
    fuel_type text,
    created_at timestamptz default now()
);

-- EU ETS reports
create table if not exists public.eu_ets_reports (
    id bigint generated by default as identity primary key,
    reporting_period text not null,
    start_date date not null,
    end_date date not null,
    total_emissions_tonnes numeric not null,
    status text not null default 'draft',
    generated_at timestamptz default now(),
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

-- ============================================================================
-- SUSTAINABILITY INTELLIGENCE TABLES
-- ============================================================================

-- CO2 intensity (gCO2/kWh) time-series
create table if not exists public.co2_intensity (
    id bigint generated by default as identity primary key,
    timestamp timestamptz not null,
    co2_intensity_g_per_kwh numeric not null,
    created_at timestamptz default now()
);

-- Generation mix (MW) by technology with renewable share
create table if not exists public.generation_mix (
    id bigint generated by default as identity primary key,
    timestamp timestamptz not null,
    hydro_mw numeric not null,
    wind_mw numeric not null,
    solar_mw numeric not null,
    nuclear_mw numeric not null,
    fossil_mw numeric not null,
    total_mw numeric not null,
    renewable_share_pct numeric not null,
    created_at timestamptz default now()
);

-- Net-zero trajectory alignment per year
create table if not exists public.netzero_alignment (
    year int primary key,
    actual_emissions_mt numeric not null,
    target_emissions_mt numeric not null,
    alignment_pct numeric not null,
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

-- ============================================================================
-- INDEXES FOR PERFORMANCE
-- ============================================================================

-- Original tables indexes
create index if not exists idx_power_plants_type on public.power_plants (plant_type);
create index if not exists idx_power_plants_country on public.power_plants (country);
create index if not exists idx_power_plant_emissions_plant_id on public.power_plant_emissions (plant_id);
create index if not exists idx_power_plant_emissions_timestamp on public.power_plant_emissions (timestamp);
create index if not exists idx_eu_ets_reports_period on public.eu_ets_reports (reporting_period);
create index if not exists idx_eu_ets_reports_status on public.eu_ets_reports (status);

-- Sustainability intelligence indexes
create index if not exists idx_co2_intensity_timestamp on public.co2_intensity (timestamp);
create index if not exists idx_generation_mix_timestamp on public.generation_mix (timestamp);
create index if not exists idx_netzero_alignment_year on public.netzero_alignment (year);

-- Composite indexes for common queries
create index if not exists idx_co2_intensity_ts_desc on public.co2_intensity (timestamp desc);
create index if not exists idx_generation_mix_ts_desc on public.generation_mix (timestamp desc);
create index if not exists idx_power_plant_emissions_ts_desc on public.power_plant_emissions (timestamp desc);

-- ============================================================================
-- ROW LEVEL SECURITY POLICIES
-- ============================================================================

-- Enable RLS on all tables
alter table public.power_plants enable row level security;
alter table public.power_plant_emissions enable row level security;
alter table public.eu_ets_reports enable row level security;
alter table public.co2_intensity enable row level security;
alter table public.generation_mix enable row level security;
alter table public.netzero_alignment enable row level security;

-- Power plants policies
drop policy if exists "power_plants anon read" on public.power_plants;
create policy "power_plants anon read" on public.power_plants for select using (true);
drop policy if exists "power_plants anon insert" on public.power_plants;
create policy "power_plants anon insert" on public.power_plants for insert with check (true);
drop policy if exists "power_plants anon update" on public.power_plants;
create policy "power_plants anon update" on public.power_plants for update using (true);

-- Power plant emissions policies
drop policy if exists "power_plant_emissions anon read" on public.power_plant_emissions;
create policy "power_plant_emissions anon read" on public.power_plant_emissions for select using (true);
drop policy if exists "power_plant_emissions anon insert" on public.power_plant_emissions;
create policy "power_plant_emissions anon insert" on public.power_plant_emissions for insert with check (true);

-- EU ETS reports policies
drop policy if exists "eu_ets_reports anon read" on public.eu_ets_reports;
create policy "eu_ets_reports anon read" on public.eu_ets_reports for select using (true);
drop policy if exists "eu_ets_reports anon insert" on public.eu_ets_reports;
create policy "eu_ets_reports anon insert" on public.eu_ets_reports for insert with check (true);
drop policy if exists "eu_ets_reports anon update" on public.eu_ets_reports;
create policy "eu_ets_reports anon update" on public.eu_ets_reports for update using (true);

-- CO2 intensity policies
drop policy if exists "co2_intensity anon read" on public.co2_intensity;
create policy "co2_intensity anon read" on public.co2_intensity for select using (true);
drop policy if exists "co2_intensity anon insert" on public.co2_intensity;
create policy "co2_intensity anon insert" on public.co2_intensity for insert with check (true);

-- Generation mix policies
drop policy if exists "generation_mix anon read" on public.generation_mix;
create policy "generation_mix anon read" on public.generation_mix for select using (true);
drop policy if exists "generation_mix anon insert" on public.generation_mix;
create policy "generation_mix anon insert" on public.generation_mix for insert with check (true);

-- Net-zero alignment policies
drop policy if exists "netzero_alignment anon read" on public.netzero_alignment;
create policy "netzero_alignment anon read" on public.netzero_alignment for select using (true);
drop policy if exists "netzero_alignment anon insert" on public.netzero_alignment;
create policy "netzero_alignment anon insert" on public.netzero_alignment for insert with check (true);
drop policy if exists "netzero_alignment anon update" on public.netzero_alignment;
create policy "netzero_alignment anon update" on public.netzero_alignment for update using (true);

-- ============================================================================
-- FUNCTIONS AND TRIGGERS
-- ============================================================================

-- Function to update updated_at timestamp
create or replace function update_updated_at_column()
returns trigger as $$
begin
    new.updated_at = now();
    return new;
end;
$$ language plpgsql;

-- Triggers for updated_at
create trigger update_power_plants_updated_at before update on public.power_plants
    for each row execute function update_updated_at_column();

create trigger update_eu_ets_reports_updated_at before update on public.eu_ets_reports
    for each row execute function update_updated_at_column();

create trigger update_netzero_alignment_updated_at before update on public.netzero_alignment
    for each row execute function update_updated_at_column();

-- ============================================================================
-- VIEWS FOR COMMON QUERIES
-- ============================================================================

-- View for latest sustainability metrics
create or replace view public.latest_sustainability_metrics as
select 
    (select co2_intensity_g_per_kwh from public.co2_intensity order by timestamp desc limit 1) as latest_co2_intensity,
    (select renewable_share_pct from public.generation_mix order by timestamp desc limit 1) as latest_renewable_share,
    (select alignment_pct from public.netzero_alignment order by year desc limit 1) as latest_netzero_alignment,
    (select count(*) from public.co2_intensity) as co2_data_points,
    (select count(*) from public.generation_mix) as generation_data_points,
    (select count(*) from public.netzero_alignment) as netzero_data_points;

-- View for power plant summary
create or replace view public.power_plant_summary as
select 
    pp.id,
    pp.plant_name,
    pp.plant_type,
    pp.capacity_mw,
    pp.location,
    pp.country,
    count(ppe.id) as emission_records_count,
    sum(ppe.co2_emissions_tonnes) as total_emissions_tonnes,
    avg(ppe.efficiency_pct) as avg_efficiency_pct,
    max(ppe.timestamp) as last_emission_record
from public.power_plants pp
left join public.power_plant_emissions ppe on pp.id = ppe.plant_id
group by pp.id, pp.plant_name, pp.plant_type, pp.capacity_mw, pp.location, pp.country;

-- ============================================================================
-- SAMPLE DATA (for development/testing)
-- ============================================================================

-- Insert sample power plants
insert into public.power_plants (plant_name, plant_type, capacity_mw, location, country, commissioning_date) values
('Solar Farm Alpha', 'Solar', 50.0, 'California, USA', 'USA', '2020-01-15'),
('Wind Park Beta', 'Wind', 100.0, 'Texas, USA', 'USA', '2019-06-20'),
('Coal Plant Gamma', 'Coal', 500.0, 'Ohio, USA', 'USA', '1985-03-10'),
('Nuclear Plant Delta', 'Nuclear', 1000.0, 'Pennsylvania, USA', 'USA', '1978-11-05'),
('Hydro Plant Epsilon', 'Hydro', 200.0, 'Washington, USA', 'USA', '1992-08-12')
on conflict do nothing;

-- Insert sample net-zero alignment data
insert into public.netzero_alignment (year, actual_emissions_mt, target_emissions_mt, alignment_pct) values
(2020, 30.0, 30.0, 100.0),
(2021, 29.0, 29.0, 100.0),
(2022, 28.0, 28.0, 100.0),
(2023, 27.0, 27.0, 100.0),
(2024, 26.0, 26.0, 100.0),
(2025, 25.0, 25.0, 100.0)
on conflict (year) do update set
    actual_emissions_mt = excluded.actual_emissions_mt,
    target_emissions_mt = excluded.target_emissions_mt,
    alignment_pct = excluded.alignment_pct,
    updated_at = now();

-- ============================================================================
-- COMMENTS FOR DOCUMENTATION
-- ============================================================================

comment on table public.power_plants is 'Power plant master data including capacity and location information';
comment on table public.power_plant_emissions is 'Time-series emissions data from individual power plants';
comment on table public.eu_ets_reports is 'EU ETS compliance reports and emissions summaries';
comment on table public.co2_intensity is 'System-wide CO2 intensity metrics over time';
comment on table public.generation_mix is 'Power generation mix by technology type over time';
comment on table public.netzero_alignment is 'Annual net-zero trajectory alignment metrics';

comment on view public.latest_sustainability_metrics is 'Latest values for key sustainability metrics';
comment on view public.power_plant_summary is 'Aggregated power plant data with emission summaries';
